### ISSUE TITLE
slsparser produces a different property path than expected from SHACL test suite

### ISSUE THREAD

**Issue by lucascool12** [MaximeJakubowski/sls_project#8]
Both path-strange tests from the SHACL test suite ([strange-path001.ttl](https://github.com/w3c/data-shapes/blob/6f9248970f4081c23e99d4d599b441d690f5403a/data-shapes-test-suite/tests/core/path/path-strange-001.ttl) and [strange-path002.ttl](https://github.com/w3c/data-shapes/blob/6f9248970f4081c23e99d4d599b441d690f5403a/data-shapes-test-suite/tests/core/path/path-strange-002.ttl)) produce a PANode different than the one specified in the tests validation result.

This is the tree for strange-path001.ttl:
```
http://datashapes.org/sh/tests/core/path/path-sequence-001.test#s1 
(Op.FORALL  cc=None  
 (POp.INV  
  (POp.PROP  rdflib.term.URIRef('http://datashapes.org/sh/tests/core/path/path-sequence-001.test#p')))
 
 (Op.COUNTRANGE  cc=http://www.w3.org/ns/shacl#ClassConstraintComponent  rdflib.term.Literal('1', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer'))
  None
  
  (POp.COMP  
   (POp.PROP  rdflib.term.URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'))
   
   (POp.KLEENE  
    (POp.PROP  rdflib.term.URIRef('http://www.w3.org/2000/01/rdf-schema#subClassOf'))))
  
  (Op.HASVALUE  cc=None  rdflib.term.URIRef('http://datashapes.org/sh/tests/core/path/path-sequence-001.test#C'))))
```
Here we can see that it generates a inverse path for the PANode in the forall.
In the validation report of the test case the result path is: `( ex:p ex:q )` which is different from the PANode seen above.
strange-path002.ttl has the same problem.

**Comment by MaximeJakubowski** [comment]
What is going on is that the path is **almost** ambigous. The path is a blank node that represents two things:
- a sequence path 
- an inverse path
My implementation chooses one of them: the inverse path. 

But the specification is very tricky, it states:
> A node in an RDF graph is a [well-formed](https://www.w3.org/TR/shacl/#dfn-well-formed) SHACL property path p if it satisfies exactly one of the syntax rules in the following sub-sections.

And this example  **seems** to satisfy two syntax rules: both the one for a sequence path and the one for an inverse path. But it is not true! And I missed it before. It is true that `strange-path001.ttl` satisfies that sequence path syntax rule, but it does not satisfy the inverse path! Because the inverse path syntax rule states that the blank node that represents the path must be the subject of **exactly one** triple. And here, this is not true.

I think this is really ugly --- but what is correct, is correct. This should be patched, and I can do it sometime this week. However, it is not that much of a priority.

**Comment by MaximeJakubowski** [comment]
It is fixed, added a test for it.
